#!/bin/bash

if [ ! -d libdtw ]; then
  git clone https://github.com/chunan/libdtw.git
fi

if [ ! -d libfeature ]; then
  git clone https://github.com/chunan/libfeature.git
fi

if [ ! -d libutility ]; then
  git clone https://github.com/chunan/libutility.git
fi

if [ ! -d libsegtree ]; then
  git clone https://github.com/chunan/libsegtree.git
fi

mkdir -p include/
if [ ! -f include/cmdparser.h ]; then
  wget https://raw.githubusercontent.com/botonchou/utility/master/include/cmdparser.h -P include/
fi

cd libdtw/ && sed -i "s%-Wall -Werror%-w%g" Makefile && make && cd -
cp -r libdtw/test/data/ ./
cd libfeature/ && make && cd -
cd libfeature/ && make && cd -
cd libfeature/ && make && cd -

make
